### ISSUE TITLE
Escape hatch to access sqljs db object for non reactive queries

### ISSUE THREAD

**Issue by kdabir** [kikko-land/kikko#100]
How can one access the underlying sqljs db object for the sqlite db created by kikko. It is required for executing low level, non-reactive queries (e.q. `SELECT name FROM sqlite_schema`)?

The use case is to create embedded SQL editor and a result window which allows user to run arbitrary SQL and shows results in a data grid. This is only going to be used for debugging purpose. If something like this already exists, which can work out of the box, i'd be more than happy to try it out.

FWIW I am using the absurd web backend with kikko, and could find if there is any way to look at the data/database created by the app.

**Comment by quolpr** [comment]
@kdabir hey! Is https://kikko-doc.netlify.app/react-integration/hooks#usedb--usedbstrict what you need (useDb/useDbStrict)?

> FWIW I am using the absurd web backend with kikko, and could find if there is any way to look at the data/database created by the app.

Nope, there is no way. I hope somebody will build DB viewer 🙂 Then it could be integrated as chrome extension
