### ISSUE TITLE
Towards 1.0 release

### ISSUE THREAD

**Issue by quolpr** [kikko-land/kikko#69]
What remains to do before stable 1.0 release

## Overall
- [x] ~~Consider ``` useQuery`SELECT * FROM ${table('notes')} ``` hook api syntax~~ don't want to complicate the api
- [ ] Fix #64 
- [x] Remove `query-builder`, `sql` packages; use `boono` instead. Remove query builder usage except query builder doc(I don't want users to force use the query builder)
- [ ] Add nice gif with vscode coding example
- [x] Think about better hooks naming. Currently, `react-query` has `useQuery`, and we have `useQuery` hook too
- [ ] Move transaction handler to adapter level. That's, for example, unlock transaction support at shared worker
- [ ] Remove query builders example from docs

## React
- [x] ~~Use use-sync-external~~ actually this api is about sync not async code. Could be useful for cache
- [ ] Add doc about multi DB support
- [ ] Update docs with new react api (including installation guides). Update all example

Also, there are some options what we can do with Suspense api. When it becomes stable, I think I will release a new major version that breaks compatibility with versions before (but not sure 100%). I want to use Suspense on the first render, and then use stale while revalidate strategy (how it behaves right now).

Some inspiration https://observable-hooks.js.org/guide/render-as-you-fetch-suspense.html#observable-resource
## Vue
- [ ] Add multi DB support for VUE the same way as we do for React

**Comment by quolpr** [comment]
@astahmer oh you are right! Yep, it's better to think about other names to not conflict with react-query 🤔 I added to the plan

**Comment by astahmer** [comment]
I went with [`useDbQuery`](https://github.com/astahmer/vite-kikko-models/blob/main/src/db-client.ts#L52) if that helps
