### ISSUE TITLE
First click does not re-render 

### ISSUE THREAD

**Issue by kdabir** [kikko-land/kikko#87]
**Context:**

Since I upgraded to the following, I am noticing weird behaviour which might be a a regression issue with kikko or something is wrong at my end.

```
        "@kikko-land/kikko": "^0.7.0",
        "@kikko-land/react": "^0.6.2",
```

**Issue:**
The first click is not triggering the re-render of the UI, although I can see the action taking place in the console. See the gif.

![Screen Cast 2022-11-06 at 10 36 42 AM](https://user-images.githubusercontent.com/735240/200155218-0871d240-ae71-4639-a298-3e3faaec66db.gif)

**Potential Cause**

- If I look at the console, the SELECT queries are fired first and then the INSERT/DELETE queries are executing, making the mutation look like a no-op.
- Another difference is - previously the mutations were executing in a transactions, which no longer looks like the case post upgrade.

Previously:
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/735240/200156764-a2dd7ab3-6c3c-48f0-90d9-715b9888a7ae.png">

Now:
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/735240/200156773-dee209a1-d1e6-4a09-8eea-327b6a841b87.png">

**Comment by quolpr** [comment]
Hey! Thank you for submit. Do you use wa-sqlite? It doesn't work with new API correctly, going to fix it 🙂

**Comment by kdabir** [comment]
no, I am using absurd-sql backend

```
        "@kikko-land/absurd-web-backend": "^0.7.0",
        "@kikko-land/kikko": "^0.7.0",
        "@kikko-land/react": "^0.6.2",
        "@kikko-land/sql.js": "^1.6.8",

```

**Comment by quolpr** [comment]
Oh, I see, have the same issue. Fixing

**Comment by quolpr** [comment]
Should be fixed now 🙂

**Comment by kdabir** [comment]
Yes, it's fixed now
