### ISSUE TITLE
vite + pnpm + wa-sqlite

### ISSUE THREAD

**Issue by astahmer** [kikko-land/kikko#92]
hey, while I was upgrading my repo (hadnt touched it for 20+days) after the fluent api changes PR got merged etc, and I thought about trying to use `wa-sqlite` to get rid of the specific COEP/COOP issues

```ts
// vite.config.ts 
// needed for @kikko-land/absurd-web-backend

 server: {
        headers: {
            "Cross-Origin-Embedder-Policy": "require-corp",
            "Cross-Origin-Opener-Policy": "same-origin",
        },
    },
```

so I swapped this:

```ts
import { absurdWebBackend } from "@kikko-land/absurd-web-backend";
import sqlWasmUrl from "@kikko-land/sql.js/dist/sql-wasm.wasm?url";

const backend = absurdWebBackend({ wasmUrl: sqlWasmUrl });
```

for this:

```ts
import { waSqliteWebBackend } from "@kikko-land/wa-sqlite-web-backend";
import sqlWasmUrl from "wa-sqlite/dist/wa-sqlite-async.wasm?url";

const backend = waSqliteWebBackend({ wasmUrl: sqlWasmUrl });
```

but the migrationsPlugin seems buggy, as if it didnt detect that migrations were already run
this error shows in the browser console :
![Screenshot 2022-11-09 at 23 37 07](https://user-images.githubusercontent.com/47224540/200957279-4131cd2e-9078-4219-b229-b41f0e8b2ee4.png)

I already tried clearing site data + manually removing every indexed dbs
Any idea on how to solve that ?

**Comment by quolpr** [comment]
I see. It happens due to react Strict Mode. Fix on the way 🙂

**Comment by quolpr** [comment]
It should be fixed now. Also, don't forget to upgrade wa-sqlite — I made some race condition fix 🙂

**Comment by astahmer** [comment]
hey, just tried upgrading but it still seems buggy, am i doing something wrong ?
![Screenshot 2022-11-12 at 16 01 36](https://user-images.githubusercontent.com/47224540/201480243-c42854dd-9d8e-4d98-9501-955f928dceb8.png)

this is the [deps upgrade commit](https://github.com/astahmer/vite-kikko-models/commit/19f75353dcb93cd8d08669d9787066451cd36e97)

**Comment by quolpr** [comment]
@astahmer oh I found the reason. It seems wa-sqlite doesn't support long int. But if you will take `new Date().getTime()` as ID it will work perfectly 🙂

It seems I will need to create an issue at wa-sqlite about this 🤔
